server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shcheol/spring-cloud-config
          default-label: main
#          username:
#          password:
