server:
  ## random port
  port: 0
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: customer-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
  datasource:
    url: ENC(S7oD+0XH91BYG/RHyVPrSJeqEOxtHpIEbRmiNIgCyylJJXFvucSI9zoNLNfQ6exjxUV7Dtwaedg=)
    username: ENC(O7X+XjZySqGansb61khTfg0h+VYWzeka)
    password: ENC(fTghhInL2PJjPioJiTHpXAhaPmhERI88)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

token:
  secret: mySecret
  expiration: 3600000



