server:
  port: 0
spring:
  application:
    name: websocket-service
  config:
    import: "optional:configserver:http://152.67.205.195:8888/"
  kafka:
    bootstrap-servers: ENC(gXzmjPYMF978IUqq/a1TfTyzeA2fnmqHQR7gWiFYeA7W1N+03uTJZgWK+5ZOZXFrScFDsazkU8SAr9cWwb3JxSxJjcMBPvtC)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

redis:
  host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)
  port: 6666