server:
  port: 0
spring:
  application:
    name: websocket-service
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
  kafka:
    bootstrap-servers: ENC(gXzmjPYMF978IUqq/a1TfTyzeA2fnmqHQR7gWiFYeA7W1N+03uTJZgWK+5ZOZXFrScFDsazkU8SAr9cWwb3JxSxJjcMBPvtC)
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)
