server:
  ## random port
  port: 0
  error:
    whitelabel:
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
  datasource:
    url: ENC(AF1grG/tnJIh1T0OPckAAdbwg8juIt5YwYZuqgUHZnzEQdng1XwZp/1EpErrIYulMdLdvFgyN/JtLC2o1CwOWnaIOdXzykzAuwzQA2knHw8=)
    username: ENC(j+10aWZUDLrHRFOy6wo5JQ==)
    password: ENC(8AvrvIm/Ria2OTgXu6tsqhToqOb0mI/I)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
  kafka:
    bootstrap-servers: ENC(gXzmjPYMF978IUqq/a1TfTyzeA2fnmqHQR7gWiFYeA7W1N+03uTJZgWK+5ZOZXFrScFDsazkU8SAr9cWwb3JxSxJjcMBPvtC)
#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)
    web:
      pageable:
        default-page-size: 21
        max-page-size: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"

