server:
  ## random port
  port: 0
  error:
    whitelabel:
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://152.67.205.195:8888/"
  datasource:
    url: ENC(djOzr0kNAAemNow17fcj9waDqB70v/ypMijPlI4INIpK+UmXRv5TLSZHRCH8FxH80gBsQ10utlk=)
    username: ENC(hU8887xxjH52qa4MSQzANw==)
    password: ENC(r9myhe9/aQ1shGTIdFtg8AWZj289Fgpg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ENC(gXzmjPYMF978IUqq/a1TfTyzeA2fnmqHQR7gWiFYeA7W1N+03uTJZgWK+5ZOZXFrScFDsazkU8SAr9cWwb3JxSxJjcMBPvtC)
  cloud:
    openfeign:
#      circuitbreaker:
#        enabled: true
#        alphanumeric-ids:
#          enabled: true
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 3000
            loggerLevel: basic
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50
resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: true


logging:
  level:
    root: info
    com.mosinsa: debug
    org.hibernate.type: trace
    org.springframework.jdbc.core: trace