server:
  ## random port
  port: 0
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
  datasource:
    url: ENC(djOzr0kNAAemNow17fcj9waDqB70v/ypMijPlI4INIpK+UmXRv5TLSZHRCH8FxH80gBsQ10utlk=)
    username: ENC(hU8887xxjH52qa4MSQzANw==)
    password: ENC(r9myhe9/aQ1shGTIdFtg8AWZj289Fgpg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html
  kafka:
    bootstrap-servers: ENC(gXzmjPYMF978IUqq/a1TfTyzeA2fnmqHQR7gWiFYeA7W1N+03uTJZgWK+5ZOZXFrScFDsazkU8SAr9cWwb3JxSxJjcMBPvtC)
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)
management:
  endpoints:
    web:
      exposure:
        include: "*"

