server:
  port: 8000

spring:
  application:
    name: apigateway-service
  config:
    import: "optional:configserver:http://152.67.205.195:8888/"
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
