server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

token:
  access:
    secret: access_secret
    expiration: 3600000
  refresh:
    secret: refresh_secret
    expiration: 1209600000