server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://127.0.0.1:8888/"
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#            - Path=/customer-service/**

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans