server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#            - Path=/customer-service/**

