spring:
  # H2 Setting
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver  # dev only, prod db : mysql
#    url: jdbc:h2:~/test
#    username: sa
#    password: test123

  # MySQL Setting
  datasource:
#    url: ENC(VdrdVvzXoagNeTVF9SOKNPXPUHCuDjFy82UrHh6jpuDZ5cDzW/9xxs46wC22y7AIuOrSPWajuAY=)
    # batchUpdate 사용하기 위해 옵션 추가 : rewriteBatchedStatements=true
    url: ENC(gu2Rv8YdQSuvWO/1RAL5ZaSj3xSqHj21sXBlbiDPiHNbuNN9DcpQuOFHpgrKFFsABrAVmWTxxOARnfwK8klG6GqpsGOQsxBq9ZrG36CEOok=)
    username: ENC(ypZdBoAHq65B8TWe9Wdh2Q==)
    password: ENC(C0nmYFZwORpRT0lnRxdIsQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  # Security Setting
  security:
    user:
      name: test
      password: test
  data:
    redis:
      port: 6666
      host: ENC(rXYNXe7i41arx3JPRfmyB/obFH7gRdNL)
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init.sql
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
# log level Setting
logging:
  level:
    org.hibernate.type: trace
    org.springframework.jdbc.core: trace

# Embedded Tomcat Setting
server:
  port: 9090

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
